# Generated by Django 2.2.6 on 2020-01-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='condition date')),
                ('treatment', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('D', 'Deep')], default='L', max_length=1)),
                ('wig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Wig')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
