# Generated by Django 2.2.6 on 2020-01-06 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wig',
            name='types',
            field=models.ManyToManyField(to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='wig',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
